# Generated by Django 4.2.9 on 2024-02-16 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
