# Generated by Django 4.2.9 on 2024-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0003_alter_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ai_analysis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
